export const MMS_LANGUAGE_DATA = [
  ["Abidji", "abi"],
  ["Achinese", "ace"],
  ["Achagua", "aca"],
  ["Achang", "acn"],
  ["Achi", "acr"],
  ["Acoli", "ach"],
  ["Achuar-Shiwiar", "acu"],
  ["Ach\u00e9", "guq"],
  ["Adele", "ade"],
  ["Adioukrou", "adj"],
  ["Agarabi", "agd"],
  ["Aghul", "agx"],
  ["Agutaynen", "agn"],
  ["Ahanta", "aha"],
  ["Akan", "aka"],
  ["Western Kanjobal", "knj"],
  ["Akawaio", "ake"],
  ["Akeu", "aeu"],
  ["Akha", "ahk"],
  ["Akoose", "bss"],
  ["Alangan", "alj"],
  ["Albanian", "sqi"],
  ["Southern Altai", "alt"],
  ["Alune", "alp"],
  ["Alur", "alz"],
  ["Kabyle", "kab"],
  ["Ambai", "amk"],
  ["North Ambrym", "mmg"],
  ["Amharic", "amh"],
  ["Amis", "ami"],
  ["San Pedro Amuzgos Amuzgo", "azg"],
  ["Angor", "agg"],
  ["Anjam", "boj"],
  ["Anufo", "cko"],
  ["Anyin", "any"],
  ["Arabela", "arl"],
  ["Arabic", "ara"],
  ["Aralle-Tabulahan", "atq"],
  ["Aringa", "luc"],
  ["Western Armenian", "hyw"],
  ["Arop-Lokep", "apr"],
  ["Arosi", "aia"],
  ["Aruamu", "msy"],
  ["Ash\u00e1ninka", "cni"],
  ["Ash\u00e9ninka Pajonal", "cjo"],
  ["Pichis Ash\u00e9ninka", "cpu"],
  ["Ucayali-Yur\u00faa Ash\u00e9ninka", "cpb"],
  ["Assamese", "asm"],
  ["Asu (Tanzania)", "asa"],
  ["Teso", "teo"],
  ["Atti\u00e9", "ati"],
  ["Eastern Maroon Creole", "djk"],
  ["Avaric", "ava"],
  ["Avatime", "avn"],
  ["Avokaya", "avu"],
  ["Awa (Papua New Guinea)", "awb"],
  ["Awa-Cuaiquer", "kwi"],
  ["Awadhi", "awa"],
  ["Aguaruna", "agr"],
  ["Aguacateco", "agu"],
  ["Central Aymara", "ayr"],
  ["Ayoreo", "ayo"],
  ["Abellen Ayta", "abp"],
  ["Mag-Indi Ayta", "blx"],
  ["Mag-antsi Ayta", "sgb"],
  ["North Azerbaijani-script_cyrillic", "azj"],
  ["North Azerbaijani-script_latin", "azj"],
  ["South Azerbaijani", "azb"],
  ["Baatonum", "bba"],
  ["Bada (Indonesia)", "bhz"],
  ["Baelelea", "bvc"],
  ["Bagheli", "bfy"],
  ["Bagri", "bgq"],
  ["Bahnar", "bdq"],
  ["Baka (South Sudan)", "bdh"],
  ["Bakhtiari", "bqi"],
  ["Bakw\u00e9", "bjw"],
  ["Balantak", "blz"],
  ["Balinese", "ban"],
  ["Southern Balochi-script_latin", "bcc"],
  ["Southern Balochi-script_arabic", "bcc"],
  ["Bambara", "bam"],
  ["Bambam", "ptu"],
  ["Bana", "bcw"],
  ["Bandial", "bqj"],
  ["Bantoanon", "bno"],
  ["Barai", "bbb"],
  ["Bari", "bfa"],
  ["Baruga", "bjz"],
  ["Bashkir", "bak"],
  ["Basque", "eus"],
  ["Bassa", "bsq"],
  ["Batak Angkola", "akb"],
  ["Batak Dairi", "btd"],
  ["Batak Karo", "btx"],
  ["Batak Simalungun", "bts"],
  ["Batak Toba", "bbc"],
  ["Bauzi", "bvz"],
  ["Bedjond", "bjv"],
  ["Besoa", "bep"],
  ["Bekwarra", "bkv"],
  ["Belize Kriol English", "bzj"],
  ["Bemba (Zambia)", "bem"],
  ["Benga", "bng"],
  ["Bengali", "ben"],
  ["Berom", "bom"],
  ["Bete-Bendi", "btt"],
  ["Bharia", "bha"],
  ["Bhatri", "bgw"],
  ["Bhattiyali", "bht"],
  ["Biali", "beh"],
  ["Bau Bidayuh", "sne"],
  ["Buhi'non Bikol", "ubl"],
  ["Central Bikol", "bcl"],
  ["Bimoba", "bim"],
  ["Binukid", "bkd"],
  ["Binumarien", "bjr"],
  ["Malba Birifor", "bfo"],
  ["Southern Birifor", "biv"],
  ["Bissa", "bib"],
  ["Bislama", "bis"],
  ["Bisu", "bzi"],
  ["Busa", "bqp"],
  ["Koronadal Blaan", "bpr"],
  ["Sarangani Blaan", "bps"],
  ["Southern Bobo Madar\u00e9", "bwq"],
  ["Bodo Parja", "bdv"],
  ["Boko (Benin)", "bqc"],
  ["Bokobaru", "bus"],
  ["Bola", "bnp"],
  ["Bomu", "bmq"],
  ["Bonggi", "bdg"],
  ["Bora", "boa"],
  ["Borong", "ksr"],
  ["Bor\u00f4ro", "bor"],
  ["Eastern Bru", "bru"],
  ["Buamu", "box"],
  ["Mapos Buang", "bzh"],
  ["Bughotu", "bgt"],
  ["Buglere", "sab"],
  ["Bulgarian", "bul"],
  ["Buli (Ghana)", "bwu"],
  ["Bum", "bmv"],
  ["Burmese", "mya"],
  ["Bwanabwana", "tte"],
  ["Cab\u00e9car", "cjp"],
  ["Cacua", "cbv"],
  ["Capanahua", "kaq"],
  ["Caquinte", "cot"],
  ["Carapana", "cbc"],
  ["Galibi Carib", "car"],
  ["Catalan", "cat"],
  ["Cebuano", "ceb"],
  ["Cerma", "cme"],
  ["Chachi", "cbi"],
  ["Chamacoco", "ceg"],
  ["Eastern Highland Chatino", "cly"],
  ["Nopala Chatino", "cya"],
  ["Chechen", "che"],
  ["Chhattisgarhi", "hne"],
  ["Nyanja", "nya"],
  ["Digo", "dig"],
  ["Duruma", "dug"],
  ["Bawm Chin", "bgr"],
  ["Eastern Khumi Chin", "cek"],
  ["Falam Chin", "cfm"],
  ["Hakha Chin", "cnh"],
  ["Matu Chin", "hlt"],
  ["M\u00fcn Chin", "mwq"],
  ["Tedim Chin", "ctd"],
  ["Thado Chin", "tcz"],
  ["Zyphe Chin", "zyp"],
  ["Comaltepec Chinantec", "cco"],
  ["Lalana Chinantec", "cnl"],
  ["Lealao Chinantec", "cle"],
  ["Ozumac\u00edn Chinantec", "chz"],
  ["Palantla Chinantec", "cpa"],
  ["Sochiapam Chinantec", "cso"],
  ["Tepetotutla Chinantec", "cnt"],
  ["Usila Chinantec", "cuc"],
  ["Hakka Chinese", "hak"],
  ["Min Nan Chinese", "nan"],
  ["Ngoni (Tanzania)", "xnj"],
  ["Chipaya", "cap"],
  ["Chiquitano", "cax"],
  ["Chittagonian", "ctg"],
  ["Chol", "ctu"],
  ["Tabasco Chontal", "chf"],
  ["Chopi", "cce"],
  ["Iyojwa'ja Chorote", "crt"],
  ["Iyo'wujwa Chorote", "crq"],
  ["Chuj-dialect_sansebasti\u00e1ncoat\u00e1n", "cac"],
  ["Chuj-dialect_sanmateoixtat\u00e1n", "cac"],
  ["Chukot", "ckt"],
  ["Chumburung", "ncu"],
  ["Churahi", "cdj"],
  ["Chuvash", "chv"],
  ["Chort\u00ed", "caa"],
  ["Cishingini", "asg"],
  ["Cof\u00e1n", "con"],
  ["El Nayar Cora", "crn"],
  ["Santa Teresa Cora", "cok"],
  ["Plains Cree-script_latin", "crk"],
  ["Plains Cree-script_syllabics", "crk"],
  ["Crimean Tatar", "crh"],
  ["Cuiba", "cui"],
  ["Daasanach", "dsh"],
  ["Daba", "dbq"],
  ["Southern Dagaare", "dga"],
  ["Northern Dagara", "dgi"],
  ["Dagba", "dgk"],
  ["Dan-dialect_gweetaawueast", "dnj"],
  ["Dan-dialect_blowowest", "dnj"],
  ["Dangal\u00e9at", "daa"],
  ["Mid Grand Valley Dani", "dnt"],
  ["Western Dani", "dnw"],
  ["Dargwa", "dar"],
  ["Datooga", "tcc"],
  ["Dawro", "dwr"],
  ["Dedua", "ded"],
  ["Deg", "mzw"],
  ["Delo", "ntr"],
  ["Dendi (Benin)", "ddn"],
  ["Desano", "des"],
  ["Desiya", "dso"],
  ["Dhao", "nfa"],
  ["Dhimal", "dhi"],
  ["Yocobou\u00e9 Dida", "gud"],
  ["Didinga", "did"],
  ["Digaro-Mishmi", "mhu"],
  ["Northeastern Dinka", "dip"],
  ["Southwestern Dinka", "dik"],
  ["Ditammari", "tbz"],
  ["Toro So Dogon", "dts"],
  ["Dogos\u00e9", "dos"],
  ["Dogri (individual language)", "dgo"],
  ["Duri", "mvp"],
  ["Dutch", "nld"],
  ["Dza", "jen"],
  ["Dzongkha", "dzo"],
  ["Ede Idaca", "idd"],
  ["Ekajuk", "eka"],
  ["Ember\u00e1-Cat\u00edo", "cto"],
  ["Northern Ember\u00e1", "emp"],
  ["English", "eng"],
  ["Enxet", "enx"],
  ["Epena", "sja"],
  ["Erzya", "myv"],
  ["Ese", "mcq"],
  ["Ese Ejja", "ese"],
  ["Evenki", "evn"],
  ["Ezaa", "eza"],
  ["South Fali", "fal"],
  ["Faroese", "fao"],
  ["Fataleka", "far"],
  ["Fijian", "fij"],
  ["Finnish", "fin"],
  ["Fon", "fon"],
  ["Fordata", "frd"],
  ["French", "fra"],
  ["Fulah", "ful"],
  ["Fuliiru", "flr"],
  ["Mudhili Gadaba", "gau"],
  ["Gaddi", "gbk"],
  ["Gagauz-script_cyrillic", "gag"],
  ["Gagauz-script_latin", "gag"],
  ["Galela", "gbi"],
  ["Gamo", "gmv"],
  ["Ganda", "lug"],
  ["Gapapaiwa", "pwg"],
  ["Garhwali", "gbm"],
  ["Garifuna", "cab"],
  ["Garo", "grt"],
  ["Gbaya (Sudan)", "krs"],
  ["Southwest Gbaya", "gso"],
  ["Gela", "nlg"],
  ["Gen", "gej"],
  ["German", "deu"],
  ["Ghari", "gri"],
  ["Kikuyu", "kik"],
  ["Gikyode", "acd"],
  ["Gilaki", "glk"],
  ["Gofa-script_latin", "gof"],
  ["Gogo", "gog"],
  ["Gokana", "gkn"],
  ["Adilabad Gondi", "wsg"],
  ["Gonja", "gjn"],
  ["Gor", "gqr"],
  ["Gorontalo", "gor"],
  ["Gourmanch\u00e9ma", "gux"],
  ["Northern Grebo", "gbo"],
  ["Modern Greek (1453-)", "ell"],
  ["Ancient Greek (to 1453)", "grc"],
  ["Guahibo", "guh"],
  ["Guajaj\u00e1ra", "gub"],
  ["Guarani", "grn"],
  ["Guarayu", "gyr"],
  ["Guayabero", "guo"],
  ["Gude", "gde"],
  ["Gujarati", "guj"],
  ["Gulay", "gvl"],
  ["Gumuz", "guk"],
  ["Gungu", "rub"],
  ["Gwahatike", "dah"],
  ["Gwere", "gwr"],
  ["Gwich\u02bcin", "gwi"],
  ["Haitian", "hat"],
  ["Halbi", "hlb"],
  ["Hamer-Banna", "amf"],
  ["Hanga", "hag"],
  ["Hanunoo", "hnn"],
  ["Haryanvi", "bgc"],
  ["Hatam", "had"],
  ["Hausa", "hau"],
  ["Hawai'i Creole English", "hwc"],
  ["Sabu", "hvn"],
  ["Haya", "hay"],
  ["Hdi", "xed"],
  ["Hebrew", "heb"],
  ["Hehe", "heh"],
  ["Hiligaynon", "hil"],
  ["Hindi", "hin"],
  ["Fiji Hindi", "hif"],
  ["Caribbean Hindustani", "hns"],
  ["Ho", "hoc"],
  ["Holiya", "hoy"],
  ["Huastec-dialect_westernpotosino", "hus"],
  ["Huastec-dialect_centralveracruz", "hus"],
  ["San Mateo Del Mar Huave", "huv"],
  ["Huli", "hui"],
  ["Hungarian", "hun"],
  ["Hupla", "hap"],
  ["Iban", "iba"],
  ["Icelandic", "isl"],
  ["Ida'an", "dbj"],
  ["Amganad Ifugao", "ifa"],
  ["Batad Ifugao", "ifb"],
  ["Mayoyao Ifugao", "ifu"],
  ["Tuwali Ifugao", "ifk"],
  ["If\u00e8", "ife"],
  ["Ignaciano", "ign"],
  ["Ika", "ikk"],
  ["Ikwo", "iqw"],
  ["Ila", "ilb"],
  ["Iloko", "ilo"],
  ["Imbongu", "imo"],
  ["Indonesian", "ind"],
  ["Inga", "inb"],
  ["Ipili", "ipi"],
  ["Iraqw", "irk"],
  ["Islander Creole English", "icr"],
  ["Itawit", "itv"],
  ["Itelmen", "itl"],
  ["Ivbie North-Okpela-Arhe", "atg"],
  ["Ixil-dialect_sanjuancotzal", "ixl"],
  ["Ixil-dialect_sangasparchajul", "ixl"],
  ["Ixil-dialect_santamarianebaj", "ixl"],
  ["Iyo", "nca"],
  ["Izere", "izr"],
  ["Izii", "izz"],
  ["Popti'", "jac"],
  ["Jamaican Creole English", "jam"],
  ["Javanese", "jav"],
  ["Caribbean Javanese", "jvn"],
  ["Kachin", "kac"],
  ["Jola-Fonyi", "dyo"],
  ["Jola-Kasa", "csk"],
  ["Adhola", "adh"],
  ["Juang", "jun"],
  ["Jukun Takum", "jbu"],
  ["Dyula", "dyu"],
  ["Jur Modo", "bex"],
  ["Juray", "juy"],
  ["Kaansa", "gna"],
  ["Urub\u00fa-Kaapor", "urb"],
  ["Kabiy\u00e8", "kbp"],
  ["Kabwa", "cwa"],
  ["Kadazan Dusun", "dtp"],
  ["Kafa", "kbr"],
  ["Kagayanen", "cgc"],
  ["Kagulu", "kki"],
  ["Da'a Kaili", "kzf"],
  ["Ledo Kaili", "lew"],
  ["Cashibo-Cacataibo", "cbr"],
  ["Kako", "kkj"],
  ["Kakwa", "keo"],
  ["Kalagan", "kqe"],
  ["Kalanguya", "kak"],
  ["Butbut Kalinga", "kyb"],
  ["Lubuagan Kalinga", "knb"],
  ["Majukayang Kalinga", "kmd"],
  ["Tanudan Kalinga", "kml"],
  ["Keley-I Kallahan", "ify"],
  ["Kalmyk", "xal"],
  ["Kamano", "kbq"],
  ["Kamayur\u00e1", "kay"],
  ["Kambaata", "ktb"],
  ["Kamwe", "hig"],
  ["Kandawo", "gam"],
  ["Candoshi-Shapra", "cbu"],
  ["Kangri", "xnr"],
  ["Kanite", "kmu"],
  ["Kankanaey", "kne"],
  ["Kannada", "kan"],
  ["Manga Kanuri", "kby"],
  ["Pampanga", "pam"],
  ["Kaqchikel-dialect_santamar\u00edadejes\u00fas", "cak"],
  ["Kaqchikel-dialect_southcentral", "cak"],
  ["Kaqchikel-dialect_yepocapa", "cak"],
  ["Kaqchikel-dialect_western", "cak"],
  ["Kaqchikel-dialect_santodomingoxenacoj", "cak"],
  ["Kaqchikel-dialect_central", "cak"],
  ["Eastern Karaboro", "xrb"],
  ["Karachay-Balkar", "krc"],
  ["Kara-Kalpak", "kaa"],
  ["Karelian", "krl"],
  ["Pwo Northern Karen", "pww"],
  ["Kasem", "xsm"],
  ["Cashinahua", "cbs"],
  ["Kaulong", "pss"],
  ["Manumanaw Karen", "kxf"],
  ["Kayab\u00ed", "kyz"],
  ["Western Kayah", "kyu"],
  ["Kayap\u00f3", "txu"],
  ["Kazakh", "kaz"],
  ["Ndo", "ndp"],
  ["Keliko", "kbo"],
  ["Kenga", "kyq"],
  ["Kenyang", "ken"],
  ["Kera", "ker"],
  ["Ketengban", "xte"],
  ["Keyagana", "kyg"],
  ["Khakas", "kjh"],
  ["Khanty", "kca"],
  ["Khmer", "khm"],
  ["Northern Khmer", "kxm"],
  ["Khmu", "kjg"],
  ["Giryama", "nyf"],
  ["Kilivila", "kij"],
  ["Kim", "kia"],
  ["Kimaragang", "kqr"],
  ["Kimr\u00e9", "kqp"],
  ["Kinaray-A", "krj"],
  ["Kinga", "zga"],
  ["Kinyarwanda", "kin"],
  ["Pokomo", "pkb"],
  ["Kire", "geb"],
  ["Gilbertese", "gil"],
  ["Kisar", "kje"],
  ["Southern Kisi", "kss"],
  ["Tharaka", "thk"],
  ["Klao", "klu"],
  ["Kelon", "kyo"],
  ["Cogui", "kog"],
  ["Northwestern Kolami", "kfb"],
  ["Komi-Zyrian", "kpv"],
  ["Northern Bobo Madar\u00e9", "bbo"],
  ["Konkomba", "xon"],
  ["Konni", "kma"],
  ["Kono (Sierra Leone)", "kno"],
  ["Konso", "kxc"],
  ["Koonzime", "ozm"],
  ["Koorete", "kqy"],
  ["Korean", "kor"],
  ["Koreguaje", "coe"],
  ["Korupun-Sela", "kpq"],
  ["Koryak", "kpy"],
  ["Kouya", "kyf"],
  ["Koya-script_telugu", "kff"],
  ["Krio", "kri"],
  ["Kriol", "rop"],
  ["Plapo Krumen", "ktj"],
  ["Tepo Krumen", "ted"],
  ["Krung", "krr"],
  ["Kuy", "kdt"],
  ["Kukele", "kez"],
  ["Culina", "cul"],
  ["Kulung (Nepal)", "kle"],
  ["Kumam", "kdi"],
  ["Kuman (Papua New Guinea)", "kue"],
  ["Kumyk", "kum"],
  ["Border Kuna", "kvn"],
  ["San Blas Kuna", "cuk"],
  ["Kunda", "kdn"],
  ["Kuo", "xuo"],
  ["Kupia", "key"],
  ["Kupsabiny", "kpz"],
  ["Kuranko", "knk"],
  ["Northern Kurdish-script_latin", "kmr"],
  ["Northern Kurdish-script_arabic", "kmr"],
  ["Northern Kurdish-script_cyrillic", "kmr"],
  ["Alu Kurumba", "xua"],
  ["Kurukh", "kru"],
  ["Kusaal", "kus"],
  ["Kutep", "kub"],
  ["Kutu", "kdc"],
  ["Kuvi", "kxv"],
  ["Kuwaa", "blh"],
  ["Kuwaataay", "cwt"],
  ["Kwaio", "kwd"],
  ["Kwamera", "tnk"],
  ["Kwara'ae", "kwf"],
  ["Kwere", "cwe"],
  ["Kyaka", "kyc"],
  ["Kyanga", "tye"],
  ["Kirghiz", "kir"],
  ["K'iche'-dialect_north", "quc"],
  ["K'iche'-dialect_east", "quc"],
  ["K'iche'-dialect_central", "quc"],
  ["Lacandon", "lac"],
  ["Lashi", "lsi"],
  ["Ladakhi", "lbj"],
  ["Lahu", "lhu"],
  ["Lama (Togo)", "las"],
  ["Lamba", "lam"],
  ["Lamnso'", "lns"],
  ["Lampung Api", "ljp"],
  ["Lango (Uganda)", "laj"],
  ["Lao", "lao"],
  ["Latin", "lat"],
  ["Latvian", "lav"],
  ["Lauje", "law"],
  ["Western Lawa", "lcp"],
  ["Laz", "lzz"],
  ["Lele (Chad)", "lln"],
  ["Lelemi", "lef"],
  ["Saint Lucian Creole French", "acf"],
  ["Lewo", "lww"],
  ["Maru", "mhx"],
  ["Eipomek", "eip"],
  ["West-Central Limba", "lia"],
  ["Limbu", "lif"],
  ["Lingao", "onb"],
  ["Lisu", "lis"],
  ["Lobala", "loq"],
  ["Lobi", "lob"],
  ["Lokaa", "yaz"],
  ["Loko", "lok"],
  ["Lole", "llg"],
  ["Lolopo", "ycl"],
  ["Loma (Liberia)", "lom"],
  ["Lomwe", "ngl"],
  ["Malawi Lomwe", "lon"],
  ["Luang", "lex"],
  ["Lugbara", "lgg"],
  ["Luguru", "ruf"],
  ["Lukpa", "dop"],
  ["Lundayeh", "lnd"],
  ["Lutos", "ndy"],
  ["Luwo", "lwo"],
  ["Ly\u00e9l\u00e9", "lee"],
  ["Mano", "mev"],
  ["Mabaan", "mfz"],
  ["Machame", "jmc"],
  ["Macuna", "myy"],
  ["Macushi", "mbc"],
  ["Mada (Nigeria)", "mda"],
  ["Madurese", "mad"],
  ["Magahi", "mag"],
  ["Mai Brat", "ayz"],
  ["Maithili", "mai"],
  ["Maca", "mca"],
  ["Makaa", "mcp"],
  ["Makasar", "mak"],
  ["Makhuwa", "vmw"],
  ["Makhuwa-Meetto", "mgh"],
  ["Makonde", "kde"],
  ["Malagasy", "mlg"],
  ["Malay (individual language)", "zlm"],
  ["Central Malay", "pse"],
  ["Kupang Malay", "mkn"],
  ["Manado Malay", "xmm"],
  ["Malayalam", "mal"],
  ["Malayic Dayak", "xdy"],
  ["Dhivehi", "div"],
  ["Male (Ethiopia)", "mdy"],
  ["Malvi", "mup"],
  ["Mam-dialect_central", "mam"],
  ["Mam-dialect_northern", "mam"],
  ["Mam-dialect_southern", "mam"],
  ["Mam-dialect_western", "mam"],
  ["Mamasa", "mqj"],
  ["Cameroon Mambila", "mcu"],
  ["Nigeria Mambila", "mzk"],
  ["Mampruli", "maw"],
  ["Mandeali", "mjl"],
  ["Mandinka", "mnk"],
  ["Mango", "mge"],
  ["Mangseng", "mbh"],
  ["Mankanya", "knf"],
  ["Mannan", "mjv"],
  ["Matigsalug Manobo", "mbt"],
  ["Obo Manobo", "obo"],
  ["Western Bukidnon Manobo", "mbb"],
  ["Manya", "mzj"],
  ["Mapun", "sjm"],
  ["Maranao", "mrw"],
  ["Marathi", "mar"],
  ["Marba", "mpg"],
  ["Eastern Mari", "mhr"],
  ["Markweeta", "enb"],
  ["Marshallese", "mah"],
  ["Masaaba", "myx"],
  ["Maskelynes", "klv"],
  ["Matal", "mfh"],
  ["Mato", "met"],
  ["Machiguenga", "mcb"],
  ["Mop\u00e1n Maya", "mop"],
  ["Yucateco", "yua"],
  ["Mayo", "mfy"],
  ["Central Mazahua", "maz"],
  ["Ayautla Mazatec", "vmy"],
  ["Chiquihuitl\u00e1n Mazatec", "maq"],
  ["Ixcatl\u00e1n Mazatec", "mzi"],
  ["Jalapa De D\u00edaz Mazatec", "maj"],
  ["San Jer\u00f3nimo Tec\u00f3atl Mazatec-dialect_sanantonio", "maa"],
  ["San Jer\u00f3nimo Tec\u00f3atl Mazatec-dialect_sanjer\u00f3nimo", "maa"],
  ["Ma'anyan", "mhy"],
  ["Ma'di", "mhi"],
  ["Mbandja", "zmz"],
  ["Mbay", "myb"],
  ["Borei", "gai"],
  ["Mbuko", "mqb"],
  ["Mbula-Bwazza", "mbu"],
  ["Melpa", "med"],
  ["Mende (Sierra Leone)", "men"],
  ["Mengen", "mee"],
  ["Mentawai", "mwv"],
  ["Merey", "meq"],
  ["Mesme", "zim"],
  ["Meta'", "mgo"],
  ["Meyah", "mej"],
  ["Migabac", "mpp"],
  ["Minangkabau", "min"],
  ["Guambiano", "gum"],
  ["Misima-Panaeati", "mpx"],
  ["Coatl\u00e1n Mixe", "mco"],
  ["Juquila Mixe", "mxq"],
  ["Quetzaltepec Mixe", "pxm"],
  ["Totontepec Mixe", "mto"],
  ["Alacatlatzala Mixtec", "mim"],
  ["Alcozauca Mixtec", "xta"],
  ["Amoltepec Mixtec", "mbz"],
  ["Apasco-Apoala Mixtec", "mip"],
  ["Atatl\u00e1huca Mixtec", "mib"],
  ["Ayutla Mixtec", "miy"],
  ["Chayuco Mixtec", "mih"],
  ["Coatzospan Mixtec", "miz"],
  ["Diuxi-Tilantongo Mixtec", "xtd"],
  ["Jamiltepec Mixtec", "mxt"],
  ["Magdalena Pe\u00f1asco Mixtec", "xtm"],
  ["Metlat\u00f3noc Mixtec", "mxv"],
  ["Northern Tlaxiaco Mixtec", "xtn"],
  ["Ocotepec Mixtec", "mie"],
  ["Pe\u00f1oles Mixtec", "mil"],
  ["Pinotepa Nacional Mixtec", "mio"],
  ["Santa Luc\u00eda Monteverde Mixtec", "mdv"],
  ["Santa Mar\u00eda Zacatepec Mixtec", "mza"],
  ["Southern Puebla Mixtec", "mit"],
  ["Tezoatl\u00e1n Mixtec", "mxb"],
  ["Yosond\u00faa Mixtec", "mpm"],
  ["Miyobe", "soy"],
  ["Central Mnong-script_latin", "cmo"],
  ["Central Mnong-script_khmer", "cmo"],
  ["Moba", "mfq"],
  ["Mochi", "old"],
  ["North Mofu", "mfk"],
  ["Mofu-Gudur", "mif"],
  ["Mokole", "mkl"],
  ["Molima", "mox"],
  ["Moma", "myl"],
  ["Momuna", "mqf"],
  ["Mon", "mnw"],
  ["Mongolian", "mon"],
  ["Mongondow", "mog"],
  ["Morisyen", "mfe"],
  ["Moro", "mor"],
  ["Moronene", "mqn"],
  ["Moru", "mgd"],
  ["Moskona", "mtj"],
  ["Mro-Khimi Chin", "cmr"],
  ["Mualang", "mtd"],
  ["Muinane", "bmr"],
  ["Mukulu", "moz"],
  ["Mumuye", "mzm"],
  ["Muna", "mnb"],
  ["Mundani", "mnf"],
  ["Mundari", "unr"],
  ["Far Western Muria", "fmu"],
  ["Murle", "mur"],
  ["Timugon Murut", "tih"],
  ["Muthuvan", "muv"],
  ["Muyang", "muy"],
  ["Mwaghavul", "sur"],
  ["Mwan", "moa"],
  ["Mwani", "wmw"],
  ["M\u00e9nik", "tnr"],
  ["M\u00edskito", "miq"],
  ["Mossi", "mos"],
  ["M\u00fcnd\u00fc", "muh"],
  ["Naasioi", "nas"],
  ["Nad\u00ebb", "mbj"],
  ["Nafaanra", "nfr"],
  ["Kharam Naga", "kfw"],
  ["Tase Naga", "nst"],
  ["Naga Pidgin", "nag"],
  ["Central Huasteca Nahuatl", "nch"],
  ["Eastern Huasteca Nahuatl", "nhe"],
  ["Guerrero Nahuatl", "ngu"],
  ["Highland Puebla Nahuatl", "azz"],
  ["Isthmus-Mecayapan Nahuatl", "nhx"],
  ["Michoac\u00e1n Nahuatl", "ncl"],
  ["Northern Oaxaca Nahuatl", "nhy"],
  ["Northern Puebla Nahuatl", "ncj"],
  ["Sierra Negra Nahuatl", "nsu"],
  ["Southeastern Puebla Nahuatl", "npl"],
  ["Tlamacazapa Nahuatl", "nuz"],
  ["Western Huasteca Nahuatl", "nhw"],
  ["Zacatl\u00e1n-Ahuacatl\u00e1n-Tepetzintla Nahuatl", "nhi"],
  ["Nalca", "nlc"],
  ["Southern Nambiku\u00e1ra", "nab"],
  ["Nanai", "gld"],
  ["Nande", "nnb"],
  ["Napu", "npy"],
  ["P\u00e1ez", "pbb"],
  ["Nateni", "ntm"],
  ["Nawdm", "nmz"],
  ["Nawuri", "naw"],
  ["Naxi", "nxq"],
  ["Ndamba", "ndj"],
  ["Ndogo", "ndz"],
  ["Ndut", "ndv"],
  ["Newari", "new"],
  ["Ngaju", "nij"],
  ["Ngambay", "sba"],
  ["Ngangam", "gng"],
  ["Ngbaka", "nga"],
  ["Ngindo", "nnq"],
  ["Ngulu", "ngp"],
  ["Ng\u00e4bere", "gym"],
  ["Karamojong", "kdj"],
  ["Nias", "nia"],
  ["Nilamba", "nim"],
  ["Ninzo", "nin"],
  ["Nkonya", "nko"],
  ["Nogai", "nog"],
  ["Nomaande", "lem"],
  ["Nomatsiguenga", "not"],
  ["Noone", "nhu"],
  ["Ntcham", "bud"],
  ["Nuer", "nus"],
  ["Nugunu (Cameroon)", "yas"],
  ["Southern Nuni", "nnw"],
  ["Nyabwa", "nwb"],
  ["Nyakyusa-Ngonde", "nyy"],
  ["Nyankole", "nyn"],
  ["Nyaturu", "rim"],
  ["Nyindrou", "lid"],
  ["Nyole", "nuj"],
  ["Nyoro", "nyo"],
  ["Nzima", "nzi"],
  ["Obolo", "ann"],
  ["Odia", "ory"],
  ["Northwestern Ojibwa-script_latin", "ojb"],
  ["Northwestern Ojibwa-script_syllabics", "ojb"],
  ["Oku", "oku"],
  ["Bassari", "bsc"],
  ["Oroko", "bdu"],
  ["Oromo", "orm"],
  ["Orya", "ury"],
  ["Ossetian", "oss"],
  ["Mezquital Otomi", "ote"],
  ["Quer\u00e9taro Otomi", "otq"],
  ["Owa", "stn"],
  ["Paasaal", "sig"],
  ["Kullu Pahari", "kfx"],
  ["Mahasu Pahari", "bfz"],
  ["Secoya", "sey"],
  ["Northern Paiute", "pao"],
  ["Palauan", "pau"],
  ["Ruching Palaung", "pce"],
  ["Brooke's Point Palawano", "plw"],
  ["Pamona", "pmf"],
  ["Pangasinan", "pag"],
  ["Papiamento", "pap"],
  ["Paranan", "prf"],
  ["Parec\u00eds", "pab"],
  ["Parkwa", "pbi"],
  ["Patamona", "pbc"],
  ["Paumar\u00ed", "pad"],
  ["Pele-Ata", "ata"],
  ["Eastern Penan", "pez"],
  ["Pengo", "peg"],
  ["Persian", "fas"],
  ["Nigerian Pidgin", "pcm"],
  ["Pijin", "pis"],
  ["Pinyin", "pny"],
  ["Piratapuyo", "pir"],
  ["Pitjantjatjara", "pjt"],
  ["Pogolo", "poy"],
  ["Polish", "pol"],
  ["San Lu\u00eds Temalacayuca Popoloca", "pps"],
  ["San Marcos Tlacoyalco Popoloca", "pls"],
  ["Highland Popoluca", "poi"],
  ["Poqomchi'-dialect_eastern", "poh"],
  ["Poqomchi'-dialect_western", "poh"],
  ["Portuguese", "por"],
  ["Phai", "prt"],
  ["Puinave", "pui"],
  ["Panjabi", "pan"],
  ["Purepecha", "tsz"],
  ["Puroik", "suv"],
  ["P\u00e9v\u00e9", "lme"],
  ["Ayacucho Quechua", "quy"],
  ["Cajamarca Quechua", "qvc"],
  ["Cusco Quechua", "quz"],
  ["Eastern Apur\u00edmac Quechua", "qve"],
  ["Huallaga Hu\u00e1nuco Quechua", "qub"],
  ["Huamal\u00edes-Dos de Mayo Hu\u00e1nuco Quechua", "qvh"],
  ["Huaylas Ancash Quechua", "qwh"],
  ["Huaylla Wanca Quechua", "qvw"],
  ["Lambayeque Quechua", "quf"],
  ["Margos-Yarowilca-Lauricocha Quechua", "qvm"],
  ["North Bolivian Quechua", "qul"],
  ["North Jun\u00edn Quechua", "qvn"],
  ["Northern Conchucos Ancash Quechua", "qxn"],
  ["Panao Hu\u00e1nuco Quechua", "qxh"],
  ["San Mart\u00edn Quechua", "qvs"],
  ["South Bolivian Quechua", "quh"],
  ["Southern Conchucos Ancash Quechua", "qxo"],
  ["Ca\u00f1ar Highland Quichua", "qxr"],
  ["Napo Lowland Quechua", "qvo"],
  ["Northern Pastaza Quichua", "qvz"],
  ["Salasaca Highland Quichua", "qxl"],
  ["Tena Lowland Quichua", "quw"],
  ["Q'anjob'al", "kjb"],
  ["Kekch\u00ed", "kek"],
  ["Rabha", "rah"],
  ["Rajbanshi", "rjs"],
  ["Ramoaaina", "rai"],
  ["Rampi", "lje"],
  ["Ranglong", "rnl"],
  ["Rangpuri", "rkt"],
  ["Rapanui", "rap"],
  ["Ravula", "yea"],
  ["Rawang", "raw"],
  ["Rejang", "rej"],
  ["Rendille", "rel"],
  ["Riang Lang", "ril"],
  ["Rigwe", "iri"],
  ["Ringgou", "rgu"],
  ["Rohingya", "rhg"],
  ["Carpathian Romani-script_latin", "rmc"],
  ["Carpathian Romani-script_cyrillic", "rmc"],
  ["Sinte Romani", "rmo"],
  ["Vlax Romani-script_latin", "rmy"],
  ["Vlax Romani-script_cyrillic", "rmy"],
  ["Romanian", "ron"],
  ["Romblomanon", "rol"],
  ["Ron", "cla"],
  ["Ronga", "rng"],
  ["Roviana", "rug"],
  ["Rundi", "run"],
  ["Russian", "rus"],
  ["Saamia", "lsm"],
  ["Sabaot", "spy"],
  ["Sadri", "sck"],
  ["Sahu", "saj"],
  ["Sakachep", "sch"],
  ["Central Sama", "sml"],
  ["Sambal", "xsb"],
  ["Botolan Sambal", "sbl"],
  ["Samburu", "saq"],
  ["Southern Samo", "sbd"],
  ["Samoan", "smo"],
  ["Sampang", "rav"],
  ["Sangir", "sxn"],
  ["Sango", "sag"],
  ["Sangu (Tanzania)", "sbp"],
  ["Sanum\u00e1", "xsu"],
  ["Saramaccan", "srm"],
  ["Sasak", "sas"],
  ["Sa'a", "apb"],
  ["Sebat Bet Gurage", "sgw"],
  ["Sedoa", "tvw"],
  ["Sekpele", "lip"],
  ["Selaru", "slu"],
  ["Selee", "snw"],
  ["Semai", "sea"],
  ["Semelai", "sza"],
  ["Sena", "seh"],
  ["Seselwa Creole French", "crs"],
  ["Shambala", "ksb"],
  ["Shan", "shn"],
  ["Shanga", "sho"],
  ["Sharanahua", "mcd"],
  ["Chayahuita", "cbt"],
  ["Sherpa", "xsr"],
  ["Shilluk", "shk"],
  ["Shipibo-Conibo", "shp"],
  ["Shona", "sna"],
  ["Shor", "cjs"],
  ["Shuar", "jiv"],
  ["Siane", "snp"],
  ["Siang", "sya"],
  ["Sidamo", "sid"],
  ["Siona", "snn"],
  ["Siriano", "sri"],
  ["Sirmauri", "srx"],
  ["Tumulung Sisaala", "sil"],
  ["Sissala", "sld"],
  ["Siwu", "akp"],
  ["Soga", "xog"],
  ["Somali", "som"],
  ["Somba-Siawari", "bmu"],
  ["Koyra Chiini Songhay", "khq"],
  ["Koyraboro Senni Songhai", "ses"],
  ["Manikion", "mnx"],
  ["Spanish", "spa"],
  ["Sranan Tongo", "srn"],
  ["Suba", "sxb"],
  ["Western Subanon", "suc"],
  ["Sudest", "tgo"],
  ["Sukuma", "suk"],
  ["Sundanese", "sun"],
  ["Sunwar", "suz"],
  ["Surgujia", "sgj"],
  ["Susu", "sus"],
  ["Swahili (individual language)", "swh"],
  ["Swedish", "swe"],
  ["Sylheti", "syl"],
  ["Djimini Senoufo", "dyi"],
  ["Mamara Senoufo", "myk"],
  ["Supyire Senoufo", "spp"],
  ["Taabwa", "tap"],
  ["Tabaru", "tby"],
  ["Tacana", "tna"],
  ["Tachelhit", "shi"],
  ["Tado", "klw"],
  ["Tagalog", "tgl"],
  ["Calamian Tagbanwa", "tbk"],
  ["Tagin", "tgj"],
  ["Tai Dam", "blt"],
  ["North Tairora", "tbg"],
  ["South Tairora", "omw"],
  ["Tajik", "tgk"],
  ["Tajio", "tdj"],
  ["Takia", "tbc"],
  ["Talinga-Bwisi", "tlj"],
  ["Talysh", "tly"],
  ["Tawallammat Tamajaq-script_tifinagh", "ttq"],
  ["Eastern Tamang", "taj"],
  ["Tamasheq", "taq"],
  ["Tamil", "tam"],
  ["Tampulma", "tpm"],
  ["Tangoa", "tgp"],
  ["North Tanna", "tnn"],
  ["Lowland Tarahumara", "tac"],
  ["Tarifit-script_latin", "rif"],
  ["Tarifit-script_arabic", "rif"],
  ["Tatar", "tat"],
  ["Tatuyo", "tav"],
  ["Western Tawbuid", "twb"],
  ["Tboli", "tbl"],
  ["Tehit", "kps"],
  ["Tewa (Indonesia)", "twe"],
  ["Tektiteko", "ttc"],
  ["Telugu", "tel"],
  ["Tem", "kdh"],
  ["Tengger", "tes"],
  ["Tennet", "tex"],
  ["Huehuetla Tepehua", "tee"],
  ["Pisaflores Tepehua", "tpp"],
  ["Tlachichilco Tepehua", "tpt"],
  ["Southeastern Tepehuan", "stp"],
  ["Teribe", "tfr"],
  ["Termanu", "twu"],
  ["Tereno", "ter"],
  ["Tewa (USA)", "tew"],
  ["Thai", "tha"],
  ["Northern Thai", "nod"],
  ["Dangaura Tharu", "thl"],
  ["Timne", "tem"],
  ["Amdo Tibetan", "adx"],
  ["Tibetan", "bod"],
  ["Khams Tibetan", "khg"],
  ["Ticuna", "tca"],
  ["Tigrinya", "tir"],
  ["Tii", "txq"],
  ["Tikar", "tik"],
  ["Dogrib", "dgr"],
  ["Toba", "tob"],
  ["Toba-Maskoy", "tmf"],
  ["Tobanga", "tng"],
  ["Tobelo", "tlb"],
  ["Tohono O'odham", "ood"],
  ["Tok Pisin", "tpi"],
  ["Tol", "jic"],
  ["Tolaki", "lbw"],
  ["Tombonuo", "txa"],
  ["Tombulu", "tom"],
  ["Gitonga", "toh"],
  ["Tontemboan", "tnt"],
  ["Toraja-Sa'dan", "sda"],
  ["Torres Strait Creole", "tcs"],
  ["Coyutla Totonac", "toc"],
  ["Highland Totonac", "tos"],
  ["Toura (C\u00f4te d'Ivoire)", "neb"],
  ["Trinitario", "trn"],
  ["Chicahuaxtla Triqui", "trs"],
  ["Copala Triqui", "trc"],
  ["Tri\u00f3", "tri"],
  ["Colorado", "cof"],
  ["Tsakhur", "tkr"],
  ["Tsikimba", "kdl"],
  ["Tsiman\u00e9", "cas"],
  ["Tsonga", "tso"],
  ["Tucano", "tuo"],
  ["Tuma-Irumu", "iou"],
  ["Tumak", "tmc"],
  ["Central Tunebo", "tuf"],
  ["Turkish", "tur"],
  ["Turkmen-script_latin", "tuk"],
  ["Turkmen-script_arabic", "tuk"],
  ["Tuwuli", "bov"],
  ["Tuyuca", "tue"],
  ["Tyap", "kcg"],
  ["Tzeltal-dialect_bachaj\u00f3n", "tzh"],
  ["Tzeltal-dialect_tenejapa", "tzh"],
  ["Tzotzil-dialect_chenalh\u00f3", "tzo"],
  ["Tzotzil-dialect_chamula", "tzo"],
  ["Tz'utujil-dialect_western", "tzj"],
  ["Tz'utujil-dialect_eastern", "tzj"],
  ["Uab Meto", "aoz"],
  ["Udmurt", "udm"],
  ["Uduk", "udu"],
  ["Ukrainian", "ukr"],
  ["Uma", "ppk"],
  ["Umbu-Ungu", "ubu"],
  ["Urak Lawoi'", "urk"],
  ["Urarina", "ura"],
  ["Urat", "urt"],
  ["Urdu-script_devanagari", "urd"],
  ["Urdu-script_arabic", "urd"],
  ["Urdu-script_latin", "urd"],
  ["Uripiv-Wala-Rano-Atchin", "upv"],
  ["Uspanteco", "usp"],
  ["Uighur-script_arabic", "uig"],
  ["Uighur-script_cyrillic", "uig"],
  ["Uzbek-script_cyrillic", "uzb"],
  ["Vagla", "vag"],
  ["Vengo", "bav"],
  ["Vidunda", "vid"],
  ["Vietnamese", "vie"],
  ["Vili", "vif"],
  ["Vunjo", "vun"],
  ["Vute", "vut"],
  ["Parauk", "prk"],
  ["Waama", "wwa"],
  ["Waima", "rro"],
  ["Waimaha", "bao"],
  ["Waiwai", "waw"],
  ["Wala", "lgl"],
  ["Wali (Ghana)", "wlx"],
  ["Wamey", "cou"],
  ["Huambisa", "hub"],
  ["Guanano", "gvc"],
  ["Wandala", "mfi"],
  ["Wapishana", "wap"],
  ["Warao", "wba"],
  ["Waray (Philippines)", "war"],
  ["Wayana", "way"],
  ["Wayuu", "guc"],
  ["Welsh", "cym"],
  ["Wersing", "kvw"],
  ["Whitesands", "tnp"],
  ["Minica Huitoto", "hto"],
  ["Murui Huitoto", "huu"],
  ["Wolaytta-script_latin", "wal"],
  ["Wolaytta-script_ethiopic", "wal"],
  ["Wolio", "wlo"],
  ["Woun Meu", "noa"],
  ["W\u00e8 Northern", "wob"],
  ["Xaasongaxango", "kao"],
  ["Xer\u00e9nte", "xer"],
  ["Yagua", "yad"],
  ["Yakan", "yka"],
  ["Yakut", "sah"],
  ["Yala", "yba"],
  ["Angguruk Yali", "yli"],
  ["Ninia Yali", "nlk"],
  ["Yalunka", "yal"],
  ["Yamba", "yam"],
  ["Yambeta", "yat"],
  ["Yamdena", "jmd"],
  ["Yami", "tao"],
  ["Yaminahua", "yaa"],
  ["Yanesha'", "ame"],
  ["Yanomam\u00f6", "guu"],
  ["Yao", "yao"],
  ["Yaour\u00e9", "yre"],
  ["Yawa", "yva"],
  ["Yemba", "ybb"],
  ["Yine", "pib"],
  ["Baruya", "byr"],
  ["Yom", "pil"],
  ["Yoruba", "yor"],
  ["Yucuna", "ycn"],
  ["Central Siberian Yupik", "ess"],
  ["Yuracare", "yuz"],
  ["Zaiwa", "atb"],
  ["Zande (individual language)", "zne"],
  ["Alo\u00e1pam Zapotec", "zaq"],
  ["Amatl\u00e1n Zapotec", "zpo"],
  ["Cajonos Zapotec", "zad"],
  ["Choapan Zapotec", "zpc"],
  ["Coatecas Altas Zapotec", "zca"],
  ["Guevea De Humboldt Zapotec", "zpg"],
  ["Isthmus Zapotec", "zai"],
  ["Lachix\u00edo Zapotec", "zpl"],
  ["Miahuatl\u00e1n Zapotec", "zam"],
  ["Mitla Zapotec", "zaw"],
  ["Mixtepec Zapotec", "zpm"],
  ["Ocotl\u00e1n Zapotec", "zac"],
  ["Ozolotepec Zapotec", "zao"],
  ["Quioquitani-Quier\u00ed Zapotec", "ztq"],
  ["Rinc\u00f3n Zapotec", "zar"],
  ["San Vicente Coatl\u00e1n Zapotec", "zpt"],
  ["Santa Mar\u00eda Quiegolani Zapotec", "zpi"],
  ["Santo Domingo Albarradas Zapotec", "zas"],
  ["Sierra de Ju\u00e1rez Zapotec", "zaa"],
  ["Texmelucan Zapotec", "zpz"],
  ["Western Tlacolula Valley Zapotec", "zab"],
  ["Yal\u00e1lag Zapotec", "zpu"],
  ["Yareni Zapotec", "zae"],
  ["Yatee Zapotec", "zty"],
  ["Yatzachi Zapotec", "zav"],
  ["Zaza", "zza"],
  ["Yongbei Zhuang", "zyb"],
  ["Zigula", "ziw"],
  ["Francisco Le\u00f3n Zoque", "zos"],
  ["Zulgo-Gemzek", "gnd"],
  ["Ewe", "ewe"],
];
